### PR TITLE
Milestone #1

### PR DESCRIPTION
**Pull request by nikiljos**
### Concepts Covered
- Schema & ERD

### CODE REVIEW

**Comment by nikiljos** [comment]
### Walkthrough Videos
1. https://www.loom.com/share/7e3213017bae4f2aba144dd556b93328
2. https://www.loom.com/share/385104e894634d03b0acd81ba4c4560e

<br>

> P.S. Please note that I've made slight improvements after recording the video as well.
> - Added TitleAuthors Relation in ERD
> - Requestor field in Requests table

**Comment by PRASANNAPATHI** [comment]
Explanation is fine,
1. In schema, add proper foreign key connection to 'requester'
2. In ERD, add the missed attribute 'requester' in 'Request' Entity.

**Comment by nikiljos** [comment]
I've updated the schema as you said.

Also, In ERD, I've kept it as a relation and hence I can't put the same thing as an attribute as well there right? Please clarify...

Screenshot 2023-09-25 at 11 48 28 AM

**Comment by PRASANNAPATHI** [comment]
Yeah, schema is fine now, 
ERD is also fine.

You can merge it now.

**Pull request merged**
